# vim: set fileencoding=utf-8 filetype=python :

files = ['anidb.c']

def set_options(opt):
	pass

def configure(conf):
	pass

def build(bld):
	obj = bld.new_task_gen(
		features = 'cc cshlib',
		source = files,
		target = 'hashfs_anidb',
		includes = '. ../../hashfs',
		install_path = '${PREFIX}/lib/hashfs',
		ccflags = ['-std=gnu99', '-g'],
		defines = bld.env['defines'],
		uselib = 'glib-2.0',
		uselib_local = 'anidb',
	)
