# vim: set fileencoding=utf-8 filetype=python :

anidbfs = ['anidbfs.c', 'util.c']
anidbfs_update = ['anidbfs-update.c', 'util.c']

def set_options(opt):
	pass

def configure(conf):
	for pkg in ['fuse', 'openssl']:
		if not conf.check_cfg(package = pkg, args = '--cflags --libs', uselib_store = pkg):
			return False

	for lib in ['m']:
		if not conf.check_cc(lib = lib, uselib_store = lib):
			return False


	return True

def build(bld):
	import Options

	defines = []

	if Options.options.debug:
		defines += ['DEBUG']

	obj = bld.new_task_gen(
		features = 'cc cprogram',
		source = anidbfs,
		target = 'anidbfs',
		uselib = 'fuse',
		install_path = '${PREFIX}/bin',
		ccflags = ['-std=gnu99'],
		defines = defines
	)

	obj = bld.new_task_gen(
		features = 'cc cprogram',
		source = anidbfs_update,
		target = 'anidbfs-update',
		includes = '. ../libanidb',
		install_path = '${PREFIX}/bin',
		uselib = 'openssl m',
		uselib_local = 'anidb',
		ccflags = ['-std=gnu99'],
		defines = defines
	)
